### ISSUE TITLE
Poll endpoint

### ISSUE THREAD

**Issue by sualko** [littleredbutton/bigbluebutton-api-php#101]
It seams that there is a undocumented poll API endpoint (https://github.com/bigbluebutton/bigbluebutton-api-php/issues/168):

https://github.com/bigbluebutton/bigbluebutton/blob/50b6cf48fb7fb0739e4a0deead909a978d2c8ff8/bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy#L643-L702

The format seams to be like this:

```
/setPollXML?meetingID=Demo Meeting&pollXML=<poll><title>Test Poll</title><question>Test Question</question><questionType>Test</questionType><answers><answer>Answer1</answer><answer>Answer2</answer></answers></poll>&checksum=0cc4142338cc45d4f6eacfbcfa2ea9754061e7ea
```

@GhaziTriki can you tell us, if this is save to use?

**Comment by sualko** [comment]
@ffdixon can you tell us something about this undocumented poll API endpoint?

**Comment by SamuelWei** [comment]
Close, as api endpoint doesn't work anymore. See https://github.com/bigbluebutton/bigbluebutton/pull/12432#issuecomment-1036392510
