### ISSUE TITLE
is it possible to set custom parameters in the join meeting.

### ISSUE THREAD

**Issue by joisarjignesh** [littleredbutton/bigbluebutton-api-php#117]
is it possible to set custom parameters in the join meeting ?
in the older version, we can set custom parameters in join meetings.

```
 Bigbluebutton::join([
                'meetingID' => 'tamku',
                'userName' => 'disa',
                'password' => 'attendee', //which user role want to join set password here
                'redirect' => false, //it will not redirect into bigblueserver
                'userId' =>  "54575",
                'customParameters' => [
                    'foo' => 'bar',
                    'key' => 'value'
                ]
  ])
```

**Comment by SamuelWei** [comment]
Currently we only support the userdata properties. However if other custom parameters are reequired we should add Support for it, like we did with the userdata. It could be added to the BaseParameters class.
@sualko @FelixJacobi what do you think?

**Comment by FelixJacobi** [comment]
Would be fine for me. But API parameter should be also added explicitly of course.

**Comment by SamuelWei** [comment]
I recommended a solution for the issue in: https://github.com/joisarjignesh/bigbluebutton/issues/66#issuecomment-1073231756

**Comment by SamuelWei** [comment]
Stale
