### ISSUE TITLE
PHP version is unmaintained

### ISSUE THREAD

**Issue by Yurujai** [littleredbutton/bigbluebutton-api-php#12]
Software has a unmaintained version of PHP [1].

To keep stable software I think we need to update required version of PHP.

* Now
`
"require": {
    "php": ">=5.4",
`

* New required version 
`
"require": {
    "php": "^7.2",
`

This change on master keep the BC ( backward compatibility ), community can use tagged version "<= 2.0.8" to use with another PHP version unsupported with the new required change.

I selected PHP ^7.2 because 7.1 version is on eol (end of life ) [2].

¿ What do you think about it ?

Thanks in advance!

[1] https://www.php.net/supported-versions.php
[2] https://www.php.net/eol.php

**Comment by sualko** [comment]
Can you open a new pull request? For me it's ok to bump that.

**Comment by Yurujai** [comment]
Yes, I will make a new PR with this change.

First, i wanted know opinions about it.

**Comment by SamuelWei** [comment]
This would be interesting for another PR of mine as well. With PHP >7 we can use type declarations. Should I create my new PR with the assumption that we will only support php >= 7.2

**Comment by Yurujai** [comment]
I believe that the new improvements should be compatible with PHP >= 7.2 since it allows us to make much cleaner code and use the improvements they have incorporated.

Let's not forget that the PHP community no longer supports the previous versions.

**Comment by sualko** [comment]
Ok, as a conclusion we will drop support for php < 7.2 :tada:, therefore I will merge your pr asap.
