### ISSUE TITLE
Prepare Release for 4.3 and 5.0

### ISSUE THREAD

**Issue by FelixJacobi** [littleredbutton/bigbluebutton-api-php#137]
- [x] All issues and PRs belonging to 4.3 and 5.0 milestone are closed/merged
- [x] Merge master branch to 5.0 branch
- [x] Create 4.3.0 release based on master branch
- [x] Create 4.3 version branch
- [x] Create 5.0.0 release based on 5.0 branch
- [x] Merge 5.0 branch back to master branch

**Comment by sualko** [comment]
I depend with my client on the upcoming 4.3. Are there currently any blockers, or can we release them in the near future?

**Comment by SamuelWei** [comment]
I think we can release in the new future.
We could merge #130 in 4.3 or 5.1.
I would prefer 4.3 as our php fixer currently cannot be run with php8.1

**Comment by FelixJacobi** [comment]
> I depend with my client on the upcoming 4.3. Are there currently any blockers, or can we release them in the near future?

I would wait for #130 and start releasing. There are a few changes left to be done for 5.0, but 5.0 can be released a few days/weeks after 4.3. But: New features must be merged into a 5.1 branch then, 5.0 should have the same feature set as 4.3 to ensure smoothing upgrading.

**Comment by sualko** [comment]
Hi everyone :wink:,

I prepared a release draft for 4.3. If this is fine for everyone I would like to publish it asap. Merging into 5.0 and branch creation can be done afterwards, right?

**Comment by SamuelWei** [comment]
Look good to me

**Comment by FelixJacobi** [comment]
> Hi everyone wink,
> 
> I prepared a release draft for 4.3. If this is fine for everyone I would like to publish it asap. Merging into 5.0 and branch creation can be done afterwards, right?

Correct, 5.0 is the deprecation-free release of 4.3.

**Comment by sualko** [comment]
Just want to say thanks for your great job here. I'm currently a bit short on time, but I try to come back to this project asap.

**Comment by FelixJacobi** [comment]
Created release `5.0`, so we are done here.
