### ISSUE TITLE
Deprecate password parameters

### ISSUE THREAD

**Issue by FelixJacobi** [littleredbutton/bigbluebutton-api-php#142]
See https://github.com/bigbluebutton/bigbluebutton-api-php/issues/177.

The passwords will be deprecated in BBB itself. We should follow that. As this includes method removals, the path is to deprecate in 5.1 and to remove in 6.0.

**Comment by FelixJacobi** [comment]
See #144:

[GetMeetingInfoParameters do no more require password parameter. · littleredbutton/bigbluebutton-api-php@5912586](https://github.com/littleredbutton/bigbluebutton-api-php/commit/5912586b182a2919d7ddbc712489d9d3d728bd4f) (needs clean deprecation and removal in next major version)
[Deprecate password params and new enum classes. · littleredbutton/bigbluebutton-api-php@f167def](https://github.com/littleredbutton/bigbluebutton-api-php/commit/f167defa1596a7e500e9db86a1e324339e0a782a) (needs clean deprecation and removal in next major version)

We must reimplement or cherry-pick this change from upstream.

**Comment by SamuelWei** [comment]
However it is still implemented in `EndMeetingParameters`
