### ISSUE TITLE
Support new checksum algorithm (sha256)

### ISSUE THREAD

**Issue by znerol** [littleredbutton/bigbluebutton-api-php#146]
BBB is about to switch form SHA1 to SHA256 as the checksum algorithm (see bigbluebutton/bigbluebutton#15684).

Hence, this library should allow its clients to specify which algorithm to use.

https://github.com/littleredbutton/bigbluebutton-api-php/blob/98f1a0cf330b2b18f928d9e45f4379506d5b3332/src/Util/UrlBuilder.php#L59-L69

**Comment by SamuelWei** [comment]
Yes, I noticed this change and how this will become very important soon.

**Comment by FelixJacobi** [comment]
Adding to 5.1, as 5.0 cannot get new features due to being deprecation-free release of 4.3.

**Comment by znerol** [comment]
Should one wait for #145 to be merged before opening a PR?

**Comment by SamuelWei** [comment]
Adding this feature brings a few design decisions with it.

Some possible implementation/design ideas:
- Adding hash algorithm to the constructor as the fourth argument behind the transport interface
- Just add hash algorithm as a fluent setter
- Replace base url and secret in constructor with object of a seperate class
- Remove base url and secret from constructor and replace with fluent setters


@FelixJacobi @sualko What do you think would be best future proof.
