### ISSUE TITLE
Add guest policy on MeetingParameters.

### ISSUE THREAD

**Issue by Yurujai** [littleredbutton/bigbluebutton-api-php#15]
The original issue is here:  https://github.com/bigbluebutton/bigbluebutton-api-php/issues/80

**Comment by SamuelWei** [comment]
We should also add the guest parameter to the JoinMeetingParameters, otherwise the guest settings are ignored.

https://docs.bigbluebutton.org/dev/api.html#create

> Default guestPolicy=ALWAYS_ACCEPT. Will set the guest policy for the meeting. The guest policy determines whether or not users who send a join request with guest=true will be allowed to join the meeting. Possible values are ALWAYS_ACCEPT, ALWAYS_DENY, and ASK_MODERATOR.
