### ISSUE TITLE
Release notes for 5.1

### ISSUE THREAD

**Issue by SamuelWei** [littleredbutton/bigbluebutton-api-php#166]
Suggestion for Release notes for 5.1

# Added

* Set checksum algorithm via the forth constructor parameter (default SHA-1)
* CreateMeetingParameters
  * `BreakoutRoomsGroups`
  * `disabledFeatures` and `disabledFeaturesExclude`
  * `lockSettingsHideViewersCursor`
  * `meetingCameraCap`
  * `meetingExpireIfNoUserJoinedInMinutes`
  * `meetingExpireWhenLastUserLeftInMinutes`
  * `preUploadedPresentationOverrideDefault`
  * `notifyRecordingIsOn`
  * `remindRecordingIsOn`
  * `recordFullDurationMedia`
  * `presentationUploadExternalUrl`
  * `presentationUploadExternalDescription`
* JoinMeetingParameters
  * `errorRedirectUrl`

# Changed

* CreateMeetingParameters
  * Renamed `setLockSettingsDisableNote` to `setLockSettingsDisableNotes` (`setLockSettingsDisableNote` deprecated)
* JoinMeetingParameters
  * Pass role instead of password in constructor 
* Updated PHPUnit to version 9

# Fixed
* Fix functional tests
* Fix CI not running for experimental versions

# Deprecated

* CreateMeetingParameters
  * `configToken` (old flash client parameter)
  * `setLockSettingsDisableNote` (use `setLockSettingsDisableNotes` instead)
  * `getAttendeePW` / `setAttendeePW` and `getModeratorPW` / `setModeratorPW` (use roles instead)
  * `setLockSettingsDisableNote` and `isLockSettingsDisableNote` (use disabledFeatures instead)
  * `setLearningDashboardEnabled` and `isLearningDashboardEnabled` (use disabledFeatures instead)
  * `setVirtualBackgroundsDisabled` and `isVirtualBackgroundsDisabled` (use disabledFeatures instead)
  * `setBreakoutRoomsEnabled` and `isBreakoutRoomsEnabled` (use disabledFeatures instead)
* JoinMeetingParameters
  * Password parameter in constructor (use roles instead)
* EndMeetingParameters 
  * Password parameter in constructor (not needed anymore)
* Meeting
  * `getAttendeePassword` and `getModeratorPassword` (use roles instead)

**Comment by SamuelWei** [comment]
@FelixJacobi What do you think? I think this would make it a bit more transparent what has changed and is deprecated

**Comment by FelixJacobi** [comment]
Looks to me, I will take over those and directly create a 5.1.1 release 😄 .

**Comment by SamuelWei** [comment]
@FelixJacobi What for it, I have found something else

**Comment by FelixJacobi** [comment]
> @FelixJacobi What for it, I have found something else

Ok, I will wait for a few hours ;) .

**Comment by FelixJacobi** [comment]
But: I copied the new release notes, since the state of 5.1 is already finally tagged. Fixed can be done in 5.1.1.
