### ISSUE TITLE
Update Symfony dependencies

### ISSUE THREAD

**Issue by FelixJacobi** [littleredbutton/bigbluebutton-api-php#175]
We're supporting 3.4, 4.4 and 5.x currently. 4.x and all before is EOL for a long time now and also we're not supporting currently relevant versions.

Todo: Support 5.4, 6.4 and 7.x in 6.0. Removing old versions must be done in a major release, since it is a breaking change.

**Comment by SamuelWei** [comment]
So in 6.0 we will add 5.4, 6.4, 7.x and remove all else?

**Comment by FelixJacobi** [comment]
Yes.
