### ISSUE TITLE
Improve code quality

### ISSUE THREAD

**Issue by FelixJacobi** [littleredbutton/bigbluebutton-api-php#177]
* Strict types, where missing (_could_ break compatibility)
* Return type hints, where still missing (must be done in a major release, since it breaks compatibility unlike parameter type hints)

**Comment by FelixJacobi** [comment]
Rector?

**Comment by SamuelWei** [comment]
Can psalm also do this, as we already have it installed

**Comment by FelixJacobi** [comment]
Yes, it can partly, but it's mainly focused on missing types in code. Rector is more focused on modernizing code in general. Using [IServ-GmbH/cotor: The Composer Tools Installer](https://github.com/IServ-GmbH/cotor) we can just install it and play it around with it ^^ . I will work on this in the next days.
