### ISSUE TITLE
Error during curl_exec. Error: HTTP/2 stream 1 was not closed cleanly before end of the underlying stream

### ISSUE THREAD

**Issue by cetiia** [littleredbutton/bigbluebutton-api-php#198]
Getting recordings.

Api version 2.0
Bigbluebutton 3.7

```php

use BigBlueButton\BigBlueButton;

    $bbb = new BigBlueButton($apiUrl, $apiSecret);
    $recordingParams = new GetRecordingsParameters();
    $recordingParams->setState('published');
    
    $response = $bbb->getRecordings($recordingParams);

    if ($response->failed()) {
        return [
            'error'=>''
        ];
    }

    $records = $response->getRecords();
```

**Error message:** `Error during curl_exec. Error: HTTP/2 stream 1 was not closed cleanly before end of the underlying stream`
**Error in line:** `$response = $bbb->getRecordings($recordingParams);`

**Comment by FelixJacobi** [comment]
I don't think, that this is an issue in the library. It sounds like, that the connection between client and server is the origin of the problem (packet loss?). Please check that first.
