### ISSUE TITLE
Add `allowPromoteGuestToModerator` parameter to `create`-call

### ISSUE THREAD

**Issue by tibroc** [littleredbutton/bigbluebutton-api-php#205]
Since BBB 2.7.9 and in 3.0 a `allowPromoteGuestToModerator` parameter was added to the `create`-call of BBBs API. This still needs to be added to this implementation.

References:
- https://docs.bigbluebutton.org/development/api/#get-post-create
- https://github.com/bigbluebutton/bigbluebutton/pull/20392
- https://github.com/bigbluebutton/bigbluebutton/pull/20504

**Comment by SamuelWei** [comment]
Implemented in https://github.com/littleredbutton/bigbluebutton-api-php/issues/202

**Comment by tibroc** [comment]
Oh nice, didn't catch that one.
