### ISSUE TITLE
Parse only 200 responses

### ISSUE THREAD

**Issue by sualko** [littleredbutton/bigbluebutton-api-php#33]
If the BBB api produces an 500 error, it doesn't response with valid XML. So in my opinion we should handle the response code in some way. Does someone know how BBB is using them?

**Comment by SamuelWei** [comment]
@sualko Do you know under which circumstances BBB is producing a 500 error? Would be helpful to simulate the behavior and decide what to do with it

**Comment by sualko** [comment]
I think it will produce only non-200 response codes if the server is misconfigured, but I'm not sure. That was the original cause of my request :wink:. It's not urgent, but it would help to tackle cases with wrong api urls or similar user errors.

**Comment by botris** [comment]
One such example is when you try to upload one or multiple files through `CreateMeetingParameters $createMeetingParams->addPresentation()` and/or `CreateMeetingParameters $createMeetingParams->setLogo()` and the total sizes exceeds the standard limit (2MB) then the server will return something like:
```
<html>
<head><title>413 Request Entity Too Large</title></head>
<body bgcolor="white">
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx/1.14.0 (Ubuntu)</center>
</body>
</html>
```
Which will result in an exception as the `<hr>` is never closed.
```
String could not be parsed as XML in SimpleXMLElement->__construct() (line 495 of /var/www/html/vendor/bigbluebutton/bigbluebutton-api-php/src/BigBlueButton.php).
```

**Comment by sualko** [comment]
@botris thanks for that great example. For me this definitely means we have to check the returning status code (`curl_getinfo($ch, CURLINFO_HTTP_CODE)`) and handle non 200 codes in some way.

Now the question is how we should do the error handling. Should we just throw an exception or should we return an error object? I would prefer an exception, because we already use them, but we should maybe wrap all of them (also the "could not be parsed") into our own exceptions. This way it's easier to distinguish. Thoughts?

**Comment by botris** [comment]
@sualko Yes I'd use an (empty) custom exception just so you can distinguish. Can create a PR if you want.

**Comment by sualko** [comment]
> Can create a PR if you want.

That would be nice. Than we could discuss the details at the code.
