### ISSUE TITLE
Discussion guest status

### ISSUE THREAD

**Issue by SamuelWei** [littleredbutton/bigbluebutton-api-php#36]
Currently we have the parameter guest on JoinMeetingParameters. It can be true or false. In both cases it will be sent to BBB.

However BBB has a strange way to handle the guest parameter (https://github.com/bigbluebutton/bigbluebutton/blob/c33ed683f37340e6a9d3585339fa04711cde7420/bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy#L249)
Sending the parameter with false, results in the user not beeing authenticated, which results in a wrong calculation  of the guest status (https://github.com/bigbluebutton/bigbluebutton/blob/dfbc1ef9b49e2297bb5cc6c3620fa481fb652f5a/bbb-common-web/src/main/java/org/bigbluebutton/api/domain/Meeting.java#L354)

In the BBB dev. the whole calculation was changed recently and reverted soon after for some breaking changes. (see BBB releases and the PRs on this topic)

**Solutions ideas**
1. Wait until BBB solves this behavior on their end
2. Don't send the guest parameter if it is false
3. Implement the undocumented parameter auth to set the auth attribute that is kept false in case the guest parameter is false (https://github.com/bigbluebutton/bigbluebutton/blob/c33ed683f37340e6a9d3585339fa04711cde7420/bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy#L258)

**Comment by SamuelWei** [comment]
@sualko @joisarjignesh what do you think?

**Comment by joisarjignesh** [comment]
@SamuelWei 
Don't send the guest parameter if it is false 
by default guest parameter is false 
so no need to pass guest parameter if it false

**Comment by sualko** [comment]
Oh BBB...

I'm fine with the fix. Nice catch :+1:
