### ISSUE TITLE
How to get an invitation link in BBB

### ISSUE THREAD

**Issue by shingtacs** [littleredbutton/bigbluebutton-api-php#39]
![image](https://user-images.githubusercontent.com/68360796/88740110-dc3fd500-d16e-11ea-857f-0251328aee7d.png)

I don't have that footer containing the invitation link. Only that first box.
I also tried to configure the guestPolicy=ASK_MODERATOR and even include the guest=>true whenever i create new rooms. After that, since I don't have that invitation link just like inside the footer in the picture, i just copied the url from the address bar (I know it sounds dumb but I wanna try everything even the dumbest way just to achieve this). 

It always give me this output.
![image](https://user-images.githubusercontent.com/68360796/88740401-9a635e80-d16f-11ea-97ad-d163e3fdf2d1.png)

**Comment by SamuelWei** [comment]
Hello @shingtacs,

the text shown in your screenshot can be set with the setModeratorOnlyMessage function.
The message itself needs to be generated through the frontend you are using this api with.
You cannot copy the url from inside a meeting, as it has some session variables included that cannot be used anywhere else.
The link you generate should bring you the your frontend, where you make the api calls to join new users to the meeting, set their role, check permission, etc. 

```php
$mod_message = 'To invite.... <a href="url">url</a>';
$meetingParams = new CreateMeetingParameters($meeting_id,$meeting_name);
$meetingParams->setModeratorOnlyMessage($mod_message);

```

**Comment by sualko** [comment]
I close this issue, because I think Samuel gave an excellent answer.

**Comment by shingtacs** [comment]
Thank you, Sir @SamuelWei for helping me. 
I will try that immediately. I've been away, Sir @sualko , thank you for closing this.
