### ISSUE TITLE
Fork: Generell discussion

### ISSUE THREAD

**Issue by sualko** [littleredbutton/bigbluebutton-api-php#4]
Follow up from bigbluebutton/bigbluebutton-api-php#82

Hi everyone,

I'm glad that you are willing to join forces and I really thrilled to create something big. Following a few points we should discuss or tackle from my point of view.

- [x] Who are you? Maybe everyone can introduce himself in two sentences, so that we know who we are (optional)
- [x] Organisation name. Is it ok? We can change it.
- [x] Merge pending pull requests. We should look through all pending pull requests and create pr into this fork for them.
- [x] Who will be the release manager?
- [x] Is it ok, that the master branch is protected and every pr needs at least one approval?
- [x] We should fix travis.
- [x] Readme should be updated with information why the project was forked and what has changed.

If you have more points, feel free to extend the list by editing this post.

**Comment by sualko** [comment]
> Who are you?

My name ist Klaus. I live and work in the south of Germany. I'm working in the field of computer science for several years and my biggest open source project is @jsxc, but I'm also active in the @Nextcloud and XMPP community.

**Comment by SamuelWei** [comment]
My name is Samuel Weirich. I live and work in the middle of Germany, in Hessen. I work as a university lecturer for medical informatics and am currently working on the setup/customisation of BigBlueButton at the Technische Hochschule Mittelhessen (THM) - University of Applied Sciences. At the moment we are using an adapted version of greenlight, but we want to build a new php-based version that meets our needs.

**Comment by joisarjignesh** [comment]
My name is Jignesh.I live and work in the gujarat(west of india).I work as a consultant with a company which creates educational software.

**Comment by sualko** [comment]
>  but we want to build a new php-based version that meets our needs

Sounds promising. A modern alternative would be great. For some NGOs I built an [integration for Nextcloud](https://github.com/sualko/cloud_bbb) and in the future I would love to see a modern playback player.

**Comment by sualko** [comment]
BTW hello everyone. Nice to meet you. :wave:

**Comment by joisarjignesh** [comment]
my skypeId : joisarjignesh10 and whatsApp number : +91 8000363292 same as telegram 
so we can communicate

**Comment by sualko** [comment]
I edited your post, so you don't get a massive amount of spam, but I think everyone in this group got your number as email notification.

I'm sorry, but I don't use any of those fancy modern apps. Just XMPP and mail.

**Comment by SamuelWei** [comment]
> I edited your post, so you don't get a massive amount of spam, but I think everyone in this group got your number as email notification.

Using the comment history, still everyone can see your phone number

**Comment by sualko** [comment]
> Using the comment history, everyone can still see your phone number

Just deleted the history too.

**Comment by joisarjignesh** [comment]
ok i deleted my comment

**Comment by Yurujai** [comment]
Hi everyone! 

My name is Pablo, I work in Spain as PHP Developer in "TELTEK Video Research" who works with educational software and make full integration with BBB software.

We have been "fighting" with the oficial API and we end with a private fork, we are keen to be part of this initiative.

Thanks in advance!

**Comment by sualko** [comment]
Hi @Yurujai, welcome to the resistance. It would be great if you could open pull request for your unmerged changes and close them there.

Any reservations in adding @Yurujai to the organisation?

**Comment by SamuelWei** [comment]
Hi @Yurujai, thank you for your interest in joining this team.

@sualko I have no reservations

**Comment by joisarjignesh** [comment]
Hello @Yurujai 
@sualko i have no reservations.

**Comment by Yurujai** [comment]
thanks all!

**Comment by Alfro** [comment]
Hi all,

I am Alfonso, I work with @Yurujai in TELTEK Video Research. We are very interested in BBB and will use this API extensively, so we of course would love to help out and share the same fork.

I haven't yet written any code for our fork, but I'll definitely end up contributing as well.

My 5 cents on the previous questions (if I'm not too late to the discussion).
> Who will be the release manager?

Maybe we can open an issue to talk about it separately? Starting with who would be available to do it.
> Is it ok, that the master branch is protected and every pr needs at least one approval?

Yers, in my opinion this is ideal. I don't think anybody disagreed so :+1: 
> We should fix travis

Now that it is fixed what about adding it to the requirements to merge a PR? (If it is not already)

**Comment by sualko** [comment]
@Alfro welcome to the team
