### ISSUE TITLE
Missing bannerText and bannerColor in CreateMeetingParameters

### ISSUE THREAD

**Issue by GuzziGuy** [littleredbutton/bigbluebutton-api-php#43]
These don't seem to be implemented here?

**Comment by sualko** [comment]
You are right. Would you mind to add it? Is there anything else missing.

**Comment by SamuelWei** [comment]
That's great. I just tested the feature with https://mconf.github.io/api-mate/
I'm a bit sad, there is no way to change the font color or add html content. Anyway we should move ahead and implement it.

**Comment by GuzziGuy** [comment]
Yep, it's fairly unexciting, I'd maybe only use it occasionally - but thought I'd note it since I think the goal of this fork is to fill in the API gaps :)

**Comment by SamuelWei** [comment]
Thank you. If no one else is interested, I can create a PR

**Comment by GuzziGuy** [comment]
Just another thought - and/or it may be worth adding an eg setCustom method to create/join etc to add any arbitrary parameters? That way it would be fully flexible...

**Comment by SamuelWei** [comment]
Yeah, I think doing both is a good idea

**Comment by sualko** [comment]
> Just another thought - and/or it may be worth adding an eg setCustom method to create/join etc to add any arbitrary parameters?

In my opinion an API should provide a clear and simply interface. Therefore I didn't include a way to add properties at best will, but I think it would be a good idea to restructure all parameter classes, so that they use magic getter/setter. This way it would be easier to add more properties.
