### ISSUE TITLE
401 issues in bbb-html5 after 3.2.0

### ISSUE THREAD

**Issue by ajs124** [littleredbutton/bigbluebutton-api-php#48]
I've run into some issues, most likely caused by #37.

The details are in https://github.com/sualko/cloud_bbb/issues/90, but I can reiterate some of them here, if you'd like.

**Comment by SamuelWei** [comment]
@ajs124 Yes, please give more details

**Comment by ajs124** [comment]
I observed this issue when using cloud_bbb, a nextcloud plugin using this library.
The observed behavior only occurs with version 3.2, so for now I'm running it with 3.1.

When looking at the network debugger in my browser, the only real difference in URLs seems that `guest=false` is not passed on anymore, which is because of 4f9e381e70861c7ef3d59bdb7331c3e582c58401.

Neither the commit itself neither [the corresponding PR](https://github.com/littleredbutton/bigbluebutton-api-php/pull/37) give any reason as to why this was changed.

The only relevant part of the URL "chain" looks like this, with 3.0 or 3.1.
```
https://bbb.local/bigbluebutton/api/join?meetingID=SOME_MEETING_ID&fullName=TEST_USER_NAME&password=SUPER_SECRET_PASSWORD&userID=SAME_AS_FULL_NAMEroot&createTime=1603041115852&redirect=true&joinViaHtml5=true&guest=false&checksum=SOME_CHECKSUM
https://bbb.local/html5client/join?sessionToken=SESSION_TOKEN
https://bbb.local/html5client/sockjs/info?cb=IDK_WHAT_THIS_IS
wss://bbb.local/html5client/sockjs/082/NO_IDEA_EITHER/websocket
https://bbb.local/bigbluebutton/api/enter?sessionToken=SESSION_TOKEN
https://bbb.local/html5client/locale?locale=de-DE&init=true
```

With 3.2 the first request doesn't have `guest=` as a get parameter.
This leads to the `sockjs` URL and `wss://` websocket being repeatedly requested and eventually giving up.
The console meanwhile repeatedly says `Object { error: 401, description: "Authentication timeout." }`.

**Comment by SamuelWei** [comment]
Could you provide some testing php code using this library, that work with the previous version but doesn't work with the current. Thanks.


> When looking at the network debugger in my browser, the only real difference in URLs seems that guest=false is not passed on anymore, which is because of 4f9e381.

Doing that is the correct way to do it, accordingly to the api specs: https://docs.bigbluebutton.org/dev/api.html#join

**Comment by sualko** [comment]
The code can be found here: 

https://github.com/sualko/cloud_bbb/blob/93154c955630f14fbd47ab4fc5eb7d2cb4f6f3db/lib/BigBlueButton/API.php#L81-L97

But I still think this is a config issue on your instance, because the code is working fine for many users. Do you have any special configuration? What happens if you try to join the room from a browser without an active Nextcloud session? In this case `guest=true` should be added.

**Comment by sualko** [comment]
Is there any update to this issue?

**Comment by ajs124** [comment]
k

**Comment by sualko** [comment]
If you have new information, we are glad to reopen this issue.
