### ISSUE TITLE
Update CS fixer rules

### ISSUE THREAD

**Issue by sualko** [littleredbutton/bigbluebutton-api-php#5]
Current configuration generates a warning:

```
The rules contain risky fixers (self_accessor, psr4), but they are not allowed to run. Perhaps you forget to use --allow-risky=yes option?
```

**Comment by Yurujai** [comment]
Looking at the php.cs file settings, in my opinion, I think we should change the custom settings to the generic ones, using the default values ​​provided by PhpCsFixer. 

On my projects i'm using this configuration ( its a suggestion ):

`
'@PSR2' => true,
       '@Symfony' => true,
       '@Symfony:risky' => true,
       '@PhpCsFixer' => true,
       '@PhpCsFixer:risky' => true,
       'array_syntax' => ['syntax' => 'short'],
       'list_syntax' => ['syntax' => 'short'],
       'ternary_to_null_coalescing' => true,
       'combine_nested_dirname' => true
`
What do you think about changes custom rules ?

**Comment by sualko** [comment]
> What do you think about changes custom rules ?

I fine with the current set. The most important thing for me is that there are some rules and the code looks consistent.
