### ISSUE TITLE
CustomParameter on JoinMeetingParameters

### ISSUE THREAD

**Issue by Noext** [littleredbutton/bigbluebutton-api-php#51]
Hello

in the official php sdk we can set custom parameters on the join meeting request ( see here : https://github.com/bigbluebutton/bigbluebutton-api-php/blob/1c8fb609e901c4932609608a5ab98a1c31115d63/src/Parameters/JoinMeetingParameters.php#L321 ) 

with this sdk we can only change the guest params

**Comment by SamuelWei** [comment]
Hello @Noext, what would the use case be?

**Comment by Noext** [comment]
Hello

is the documentation of BBB ( https://docs.bigbluebutton.org/2.2/customize.html )

you can add many params to the join request with the html5 client

for my use case i'm using it for those variables : userdata-bbb_custom_style, userdata-bbb_auto_swap_layout, userdata-bbb_hide_presentation

**Comment by SamuelWei** [comment]
Hello @Noext,

thank you for your explanation. We already support the userdata parameters. Have a look at this file: src/Parameters/UserDataParameters.php and as the JoinMeetingParameters class extends the UserDataParameters class you can use them for joining a meeting.

```php
$joinMeetingParams = new JoinMeetingParameters($roomid, $displayname, $password);
$joinMeetingParams->addUserData->('bbb_custom_style','content');
$joinUrl = $bbb->getJoinMeetingURL($joinMeetingParams);
```
