### ISSUE TITLE
Parameters overwrite server defaults

### ISSUE THREAD

**Issue by sualko** [littleredbutton/bigbluebutton-api-php#54]
The current implementation is setting multiple parameters to false by default. This unexpectedly overwrites server default. One example are the lock settings.

https://github.com/littleredbutton/bigbluebutton-api-php/blob/82973d891807de6e264cc0be395868cc041652a0/src/Parameters/CreateMeetingParameters.php#L1101-L1110

#49 could easily fix this and therefore your comments to the pull requests are appreciated.

EDIT #49 already solves this issue by filtering null values from the query.

**Comment by SamuelWei** [comment]
@sualko I agree, #49 would solve this. I added my review.
