### ISSUE TITLE
Wrong license in composer.json

### ISSUE THREAD

**Issue by KimBrodowski** [littleredbutton/bigbluebutton-api-php#58]
See https://github.com/bigbluebutton/bigbluebutton-api-php/issues/134

Hello,

the composer.json states this project is licensed under GPL while the LICENSE file states the project is released under LGPL.

This is a problem, since as a commercial proprietary software vendor we cannot use GPL licensed code except under very specific circumstances.

https://github.com/littleredbutton/bigbluebutton-api-php/blob/d5490b2ed7a5a9fa335ccdfee18b54a4b867c3f2/composer.json#L11

https://github.com/littleredbutton/bigbluebutton-api-php/blob/d5490b2ed7a5a9fa335ccdfee18b54a4b867c3f2/LICENSE#L1

Please correct this mistake.

Best regards,
Kim-Alexander Brodowski

**Comment by sualko** [comment]
Thanks for the hint. Since the license header in every file is also saying lgpl, this should be a no-brainer.

**Comment by SamuelWei** [comment]
I already created a branch for the fix

**Comment by sualko** [comment]
I just wanted to click "open pull request" :joy:

**Comment by sualko** [comment]
`LGPL-3.0-or-later` should be correct according to the license header.

**Comment by FelixJacobi** [comment]
> @KimBrodowski if you are using our library and have some time left, it would be great if you could test/review #49 which is a huge refactoring. Anyway thanks for mention the license issue.

Hi,

I am a colleague of @KimBrodowski, we're working together on the project which is using this library. I am planning to concentrate to this library again on next weekend especially to finalize  #57. I would also take a closer look at #49 then.
