### ISSUE TITLE
Create documentation

### ISSUE THREAD

**Issue by sualko** [littleredbutton/bigbluebutton-api-php#6]
I prefer to keep it under source control, but we could also add it to the wiki.

**Comment by SamuelWei** [comment]
What about using a nice documentation with https://github.com/squidfunk/mkdocs-material hosted with github pages

Deploy to github pages: https://github.com/mhausenblas/mkdocs-deploy-gh-pages

**Comment by sualko** [comment]
There are many ways to create a nice documentation, but I try to keep things as simple as possible. Even a lightway solution takes some time to maintain, but the overhead for a nice solution is way to much in my opinion as there is not that much to document. Just my personal opinion. Other opinions?

**Comment by SamuelWei** [comment]
No problem, let's start using the readme. We can move to something else down the road

**Comment by sualko** [comment]
As the readme was updated, I close this issue.
