### ISSUE TITLE
Secrets are not passed to workflows that are triggered by a pull request from a fork

### ISSUE THREAD

**Issue by sualko** [littleredbutton/bigbluebutton-api-php#64]
That's probably the reason why the tests for #57 and #63 are failing.

**Comment by SamuelWei** [comment]
@sualko You are right, that is a security setting to prevent others to write scripts as PR that would expose the secrets.

**Comment by sualko** [comment]
Has been fixed in 3750b1bdb034dff6eaf4b29bc15f3bc7134567ef
