### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by sualko** [littleredbutton/bigbluebutton-api-php#68]
Hi everyone. I think we are ready to release another version of this awesome API. Looking at [all changes](https://github.com/littleredbutton/bigbluebutton-api-php/compare/3.3.0...master) we probably have to make a major bump. So the next version should be 4.0.0. Any counter arguments? Otherwise I want to collect a changelog here, so please feel free to edit it or post additions in the comment section.

## Added
- add support for `putRecordingTextTrackAnchor`
- add composer scripts for cs-fixer
- add new breakout parameters for create meetings call
- add `meetingKeepEvents`, `endWhenNoModerator` and `endWhenNoModeratorDelayInMinutes` parameters to create meetings call
- we use psalm to fix code errors now
- add helper functions and constants for message keys. For example `CreateMeetingResponse::KEY_DUPLICATE_WARNING` and `$createMeetingResponse->isDuplicate()`
- add `CURLOPT_TIMEOUT` to prevent processes being stuck after connecting to server
- support for multiple transports (curl, psr, symfony, custom)

## Changed
- BREAKING only options which are set are used. In the versions below every parameter had a default value.
- move to Github actions

## Fixed
- license in composer file
- authentication of config XML
- getMeetings scalelite error
- remove getMessageKey check

## Deprecated
- Getting and setting XML configuration was only supported by the flash client which was removed in BBB 2.2. Therefore this API endpoint was removed completely from BBB 2.3.
- we adapted parameter naming to the official API. Therefore the following methods are deprecated and will be removed in one of the next releases:
```
CreateMeetingParameter:
getMeetingName() --> getName()
setMeetingName() --> setName()
getMeetingId() --> getMeetingID()
setMeetingId() --> setMeetingID()
getAttendeePassword() --> getAttendeePW()
setAttendeePassword() --> setAttendeePW()
getModeratorPassword() --> getModeratorPW()
setModeratorPassword() --> setModeratorPW()
getWelcomeMessage() --> getWelcome()
setWelcomeMessage() --> setWelcome()
getLogoutUrl() --> getLogoutURL()
setLogoutUrl() --> setLogoutURL()
isRecorded() --> isRecord()
getParentMeetingId() --> getParentMeetingID()
setParentMeetingId() --> setParentMeetingID()

DeleteRecordingsParameters:
getRecordingId() --> getRecordID()
setRecordingId() --> setRecordID()

EndMeetingParameters:
getMeetingId() --> getMeetingID()
setMeetingId() --> setMeetingID()

GetMeetingInfoParameters:
getMeetingId() --> getMeetingID()
setMeetingId() --> setMeetingID()

GetRecordingsParameters:
getMeetingId() --> getMeetingID()
setMeetingId() --> setMeetingID()
getRecordId() --> getRecordID()
setRecordId() --> setRecordID()

GetRecordingTextTracksParameters:
getRecordId() --> getRecordID()
setRecordId() --> setRecordID()

HooksCreateParameters:
getCallbackUrl() --> getCallbackURL()
setCallbackUrl() --> setCallbackURL()
getMeetingId() --> getMeetingID()
setMeetingId() --> setMeetingID()
getRaw() --> isGetRaw()

HooksDestroyParameters:
getHookId() --> getHookID()
setHookId() --> setHookID()

IsMeetingRunningParameters:
getMeetingId() --> getMeetingID()
setMeetingId() --> setMeetingID()

JoinMeetingParameters:
getMeetingId() --> getMeetingID()
setMeetingId() --> setMeetingID()
getCreationTime() --> getCreateTime()
setCreationTime() --> setCreateTime()
getUsername() --> getFullName()
setUsername() --> setFullName()
getUserId() --> getUserID()
setUserId() --> setUserID()

PublishRecordingsParameters:
getRecordId() --> getRecordID()
setRecordId() --> setRecordID()

SetConfigXMLParameters:
getMeetingId() --> getMeetingID()
setMeetingId() --> setMeetingID()

UpdateRecordingsParameters:
getRecordId() --> getRecordID()
setRecordId() --> setRecordID()
```

**Comment by SamuelWei** [comment]
I agree, it is time for a new major release, as we added a lot of new featues and deprecated quite a few old functions. Should we solve and deprecate #73 before or after the release?

**Comment by sualko** [comment]
> Should we solve and deprecate #73 before or after the release?

Since the config.xml is related to the flash client, I would remove it before we release the next version. Otherwise it would be another breaking change.

Btw I invited @FelixJacobi to the organization, because he did an excellent job and working on branches together should simplify a lot.

**Comment by sualko** [comment]
@SamuelWei @FelixJacobi everything ready for 4.0?

**Comment by FelixJacobi** [comment]
> @SamuelWei @FelixJacobi everything ready for 4.0?

From my side: Go ahead! ^^

**Comment by SamuelWei** [comment]
I agree. Thank you @sualko and @FelixJacobi for the great work leading to this release!

**Comment by SamuelWei** [comment]
@sualko Any updates?

**Comment by sualko** [comment]
@SamuelWei can you review #95? Afterwards we can publish the release.

**Comment by sualko** [comment]
Great work everyone :clap: :tada: 

It's really a pleasure to work with you and I think this release is a major improvement.
