### ISSUE TITLE
Support for PHP 8

### ISSUE THREAD

**Issue by FelixJacobi** [littleredbutton/bigbluebutton-api-php#69]
The `composer.json` and some (dev) dependencies currently does not allow to run this library on PHP 8. I guess that the code here should be almost fine and only the `composer.json` and incompatible dependencies needs to be updated.

~~~
  Problem 1
    - Root composer.json requires php ^7.2 but your php version (8.0.5) does not satisfy that requirement.
  Problem 2
    - fzaninotto/faker is locked to version v1.9.2 and an update of this package was not requested.
    - fzaninotto/faker v1.9.2 requires php ^5.3.3 || ^7.0 -> your php version (8.0.5) does not satisfy that requirement.
  Problem 3
    - php-coveralls/php-coveralls is locked to version v2.2.0 and an update of this package was not requested.
    - php-coveralls/php-coveralls v2.2.0 requires php ^5.5 || ^7.0 -> your php version (8.0.5) does not satisfy that requirement.
~~~

Therefore, I would switch the semver constraint to allow all future PHP major versions (e.g. `>=7.2`) as I guess that there will be only a few minor compatibility issues on every new PHP major version, if there should be any at all.

Finally, PHP 8 (and 8.1 directly?) should be added to the CI.

I would take a look on this in the next days.

**Comment by FelixJacobi** [comment]
Note: `faker` is considered as dead: https://marmelab.com/blog/2020/10/21/sunsetting-faker.html

It has been updated to work on PHP 8 so far, but a future PHP 9 will not be supported anymore, so it would consider to refactor it out of the tests in a later PR.

**Comment by sualko** [comment]
Great idea :+1:

**Comment by FelixJacobi** [comment]
See  #70.
