### ISSUE TITLE
Remove faker from tests

### ISSUE THREAD

**Issue by FelixJacobi** [littleredbutton/bigbluebutton-api-php#71]
`faker` is considered as dead: https://marmelab.com/blog/2020/10/21/sunsetting-faker.html

It has been updated to work on PHP 8 so far, but a future PHP 9 will not be supported anymore, so it would consider to refactor it out of the tests.

To run it with PHP 8 a kind of evil hack was required: https://github.com/littleredbutton/bigbluebutton-api-php/pull/70#discussion_r637601616

**Comment by SamuelWei** [comment]
To be honest François Zaninotto has a point, we don't need a 3MB library to create some meeting room names, welcome texts, dialing numbers and usernames.

However, it might be a solution for now to switch to the faker fork used by laravel https://github.com/FakerPHP/Faker

**Comment by FelixJacobi** [comment]
> To be honest François Zaninotto has a point, we don't need a 3MB library to create some meeting room names, welcome texts, dialing numbers and usernames.
> 
> However, it might be a solution for now to switch to the faker fork used by laravel https://github.com/FakerPHP/Faker

Good point, I will play around with it and include it in the PHP 8 if its suitable.

**Comment by FelixJacobi** [comment]
But in long term I would prefer to use more static data in tests as using random data each time mades the test kind of unpredictable. Sure it can make sense to test with random data, but I am not sure this belongs to unit and integration tests, which are mainly intended to show me, that I did not break any exsisting code.
