### ISSUE TITLE
getDefaultConfigXML fail on BBB 2.3

### ISSUE THREAD

**Issue by SamuelWei** [littleredbutton/bigbluebutton-api-php#73]
Requesting getDefaultConfigXML on BBB 2.3 will result in an error, see https://github.com/bigbluebutton/bigbluebutton/issues/12408

We should either remove this from the api or have an .env value to disable the feature, so tests no longer fail

**Comment by sualko** [comment]
For documentation: See https://github.com/bigbluebutton/bigbluebutton/pull/12432

> Removes obsolete config.xml references - remnant of the Flash client, not supported since BBB 2.2.x-2.3.x

**Comment by FelixJacobi** [comment]
I guess we should provide a proper deprecation notice. Although the calls does not have any effect at all anymore it is probably still inside of projects which using this library.

Deprecating in 4.0 and remove in 4.1? (as we currently did not have any strict roadmap like Symfony regarding Major and minor versions (only the first one allowed to remove deprecated code) as far as I can see?)

Regarding tests: I would them to a specific `@group` which is excluded by default from running.

**Comment by FelixJacobi** [comment]
See #77.

**Comment by sualko** [comment]
> Deprecating in 4.0 and remove in 4.1?

Sounds like a good idea, since we have a few deprecated methods in the next release.

> Regarding tests: I would them to a specific @group which is excluded by default from running.

:+1:
