### ISSUE TITLE
Drop HHVM from GitHub workflows?

### ISSUE THREAD

**Issue by FelixJacobi** [littleredbutton/bigbluebutton-api-php#91]
Seems to do not work anyway:

> Run hhvm vendor/bin/phpunit
>
> Fatal error: Not a Hack file in /home/runner/work/bigbluebutton-api-php/bigbluebutton-api-php/vendor/phpunit/phpunit/phpunit on line 1
> Error: Process completed with exit code 255.

(see [Split integration test suite into non-invasive integration and invasive functional suite by FelixJacobi · Pull Request #90 · littleredbutton/bigbluebutton-api-php](https://github.com/littleredbutton/bigbluebutton-api-php/pull/90/checks?check_run_id=2976403331))

HHVM dropped PHP support several years ago. I guess we can drop this job safetly.

**Comment by sualko** [comment]
Good idea. Here the blog post from 2019: https://hhvm.com/blog/2019/02/11/hhvm-4.0.0.html
